sudo: false
language: node_js
node_js:
- '8.9.0'
cache: yarn
notifications:
  email: false
  slack:
    on_success: always
before_script:
- yarn clean
script:
- yarn export
- touch out/.nojekyll
- yarn create:cname
env:
- DEPLOY_ENV="mingchi.tech" PROJ_NAME="mingchi.tech"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./out
  on:
    branch: master